use_frameworks!

target 'MyAPI_Example' do
  pod 'MyAPI', :path => '../'

  target 'MyAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
